name: Post AI
on:
  schedule:
    - cron: "0 22 * * *"
    - cron: "0 2 * * *"
    - cron: "0 6 * * *"
    - cron: "0 10 * * *"
    - cron: "0 14 * * *"
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      NG_GEMINI_KEY: ${{ secrets.NG_GEMINI_KEY }}
      NG_TG_TOKEN: ${{ secrets.NG_TG_TOKEN }}
      NG_TG_CHANNEL: ${{ secrets.NG_TG_CHANNEL }}
      NG_VK_TOKEN: ${{ secrets.NG_VK_TOKEN }}
      NG_VK_GROUP: ${{ secrets.NG_VK_GROUP }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install Pillow
      - run: python neuro.py --channel ai
